### ISSUE TITLE
Shape quality

### ISSUE THREAD

**Issue by mariosmaselli** [LingDong-/q5xjs#6]
Hey, thanks a lot for the lib, I'm testing it on a project and the js size decrease considerably.
So far the only problem that I've found is the quality of the shapes, they seem a bit more blurred and not as sharp as with p5

Any idea what can be causing this? 
not sure if is related with pixelDensity, but I notice that this also doesn't work the same way as in p5 

Thanks!

**Comment by LingDong-** [comment]
Hi! I believe it is indeed related with pixelDensity. p5.js implicitly sets `pixelDensity(2)` on retina displays.
q5.js always starts with `pixelDensity(1)` by default, as I think it produces more consistent and predictable results when accessing the `pixels[]` array.
However you can set the ratio to other values by explicitly calling e.g. `pixelDensity(2);`. The intrinsic pixel density of the device can be found with [window.devicePixelRatio](https://developer.mozilla.org/en-US/docs/Web/API/Window/devicePixelRatio) (Maybe I should wrap this one too like p5 does). Currently `pixelDensity` needs be called in `setup()` before drawing stuff, otherwise there might be some strange results with scaling.
Please let me know if you encounter more issues, thanks a lot!

**Comment by mariosmaselli** [comment]
Is actually scaling down on q5, even if I add it on the setup
https://codepen.io/mariosmaselli/pen/a3a9b31a6b7f7667153d3080b44e55a7

Is this the "normal" behaviour? should I re-scale afterwards
Thanks for the help!

<img width="457" alt="Screenshot 2020-10-03 at 23 03 40" src="https://user-images.githubusercontent.com/1336977/95000815-c1ee0180-05cc-11eb-8280-157d2da88c11.png">

**Comment by LingDong-** [comment]
Hi @mariosmaselli,

pixelDensity() needs to be called after createCanvas(), (since internally it really maps to a canvas upscale + drawing context downscale, if there's no canvas, there's nothing for it to scale :) 

Looks like p5.js is fine with either order, I'll see if it makes sense for q5 to match this behavior. Thanks for the report!

Also the current release version on cdn.jsdelivr is tiny bit out of date, I just pushed a new release from the master branch that contains a related fix to background(). Should be working once jsdelivr relinks to my new version (it takes a while) and order of createCanvas and pixelDensity is flipped!

Screenshot below is what it looks like when I manually include master branch version. I'm on a retina display too.

![image](https://user-images.githubusercontent.com/7929704/95001488-715cb100-0598-11eb-8267-731598a0b1dd.png)

Hope this helps, thanks!

**Comment by mariosmaselli** [comment]
Thanks a lot! 
Everything is working now.. 
Yeah I believe that I tried the other way around but the background was off, I updated q5 now and everything is good!

**Comment by EstebanPiacentino** [comment]
Thank you so much for this! However, when using Q5("global"), I still see the background unscaled. 
See my code below and the output:

```
new Q5("global");


function setup() {
  createCanvas(700,700);
  pixelDensity(window.devicePixelRatio);
}

function draw() {
  background(100);

  fill(150,0,0);
  rect(350,350,100,100);
  
}
```
<img width="773" alt="Captura de pantalla 2024-03-24 a las 20 10 30" src="https://github.com/LingDong-/q5xjs/assets/47774376/ca748d44-de06-4a71-9eaa-fb61b77d7bdd">

Thanks
